language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
sudo: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq postgis binutils
install:
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
script:
 - pep8 calculate
 - pyflakes calculate
 - cd docs && make html && cd ..
 - coverage run setup.py test
after_success:
  - coveralls
